(defun SEsBD (Nostile)
  (SETQ PR NIL)
  (SETQ PROB (TBLNEXT "style" T))
  (WHILE (and PROB (= pr nil))
    (SETQ NPROV (CDR (CAR (CDR PROB))))
    (IF (= (strcase NPROV) (strcase Nostile)) (SETQ PR "S"))
    (SETQ PROB (TBLNEXT "style"))
  )
  (SETq RESP PR)
)