(defun leebdex (estacion procedencia variable tipodat tipoproceso)
  (C:LIBRERIA "lee datos directos")
  (C:LIBRERIA "maximos excel")
  (C:LIBRERIA "minimos excel")
  (C:LIBRERIA "serie temporal diaria excel")
  (C:LIBRERIA "media excel")
  (C:LIBRERIA "porcentajes excel")
  (C:LIBRERIA "totales excel")
  (if (< (atoi estacion) 10000)(setq estacion (strcat "0" (itoa(atoi estacion)))))
      (setq ldat1 (directos estacion procedencia variable))
      (if (OR (= tipodat "AN") (= tipodat "ME") (= tipodat "MM"))
        (progn
          (if (= tipoproceso "MA") (setq ldat1 (maximose ldat1 tipodat variable)))
          (if (= tipoproceso "MI") (setq ldat1 (minimose ldat1 tipodat variable)))
          (if (= tipoproceso "ME") (setq ldat1 (mediae ldat1 tipodat variable)))
          (if (= tipoproceso "TO") (setq ldat1 (TOTALESe ldat1 tipodat variable)))
          (if (= tipoproceso "VC") (setq ldat1 (PORCENTAJESe ldat1 tipodat variable)))
          (if (AND (OR (= variable 1) (= variable 3)) (OR (= tipoproceso "MA") (= tipoproceso "MI") (= tipoproceso "ME")))
            (SETQ CARY 6)
          )
          (if (AND (OR (= variable 7) (= variable 8) (= variable 9)) (OR (= tipoproceso "MA") (= tipoproceso "MI") (= tipoproceso "ME")) )
            (SETQ CARY 5)
          )
          (if (= tipoproceso "TO")
            (SETQ CARY 9)
          )
          (if (= tipoproceso "VC")
            (SETQ CARY 5)
          )
          (if (and (or (= variable 2) (= variable 4) (= variable 5) (= variable 6)) (/= tipoproceso "VC"))
            (SETQ CARY 1)
          )
        )
      )
      (if (= tipodat "ST") (setq ldat1 (tempdiariae ldat1 variable)))
  (setq ldat1 ldat1)
)

(defun optimizabdiarios2 (estacion variable)
  (if (= procedencia "C")
    (progn
      (setq contcig 1)
      (setq estaciong "000000")
      (setq scierto "")
      (while (and (or (/= estacion (substr estaciong 1 5)) (/= VARIABLE (ATOI (substr estaciong 6 1)))) (< contcig controlbdacc))
        (setq estaciong (cdr (car (cdr (assoc contcig optimizadiarioc)))))
        (if (and (= estacion (substr estaciong 1 5)) (= VARIABLE (ATOI (substr estaciong 6 1)))) (setq scierto "s"))
        (setq contcig (1+ contcig))
      )
      (IF (= scierto "s")
        (setq listadat (cdr (cadr (cdr (assoc (1- contcig) optimizadiarioc)))))
        (setq listadat "")
      )
    )
    (progn
      (setq contcig 1)
      (setq estaciong "000000")
      (setq scierto "")
      (while (and (or (/= estacion (substr estaciong 1 5)) (/= VARIABLE (ATOI (substr estaciong 6 1)))) (< contcig controlbdacE))
        (setq estaciong (cdr (car (cdr (assoc contcig optimizadiarioe)))))
        (if (and (= estacion (substr estaciong 1 5)) (= VARIABLE (ATOI (substr estaciong 6 1)))) (setq scierto "s"))
        (setq contcig (1+ contcig))
      )
      (IF (= scierto "s")
        (setq listadat (cdr (cadr (cdr (assoc (1- contcig) optimizadiarioe)))))
        (setq listadat "")
      )
    )
  )
  (setq listadat listadat)
)

;(leebdex "16087" "C" 3 "ST" "")
;estacion	cadena		estacion a graficar
;procedencia	cadena		Clicom o erick
;variable	entero		variable climatica a graficar 1-9
;FECHAINI	CADENA		FECHA INICIAL A PROCESAR LOS DATOS DE LA GRAFICA formato de 4 6 o 8 caracteres segun se requiera
;tipodat	CADENA		tipo de datos a graficar "AN" "ME" "ST" "MM"
;tipoproceso	cadena		tipo de proceso a recibir la cadena (valores maximos, minimos, medios, totales, %vacios, serie temporal) "MA" "MI" "ME" "TO" "VC" "ST"