(defun rnnpp (nlist archivo)
  (setq archdim (open archivo "r"))
  (setq contadornn 0)
  (while (/= prob nlist)
    (SETQ PROB (read-line archdim))
    (setq contadornn (1+ contadornn))
  )
  (setq contadornn (1- contadornn))
  (close archdim)
  (SETq RESP contadornn)
)